### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by LukeBillo** [jsreport/jsreport-cli#16]
When installing globally via `npm install jsreport-cli -g` I get the following warnings:

```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```

Not really a huge issue, but it states that the event loop can block for a long periods of time under certain regular expressions in tough-cookie, and node-uuid is deprecated.

**Comment by bjrmatos** [comment]
hi! in next version of cli (v2), which should be released really soon, we don't use the uuid package and we updated all deps, so this warning will be gone there. thanks for the report
