### ISSUE TITLE
have a way to configure windows service logs (stdout, stderr)

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport-cli#9]
using:

`nssm set [serviceName] AppStdout \path\to\service.out.log`
`nssm set [serviceName] AppStderr \path\to\service.err.log`

can be a nice feature when testing.

**Comment by bjrmatos** [comment]
and probably some options about file rotation for these files

**Comment by pofider** [comment]
Isn't the jsreport log enough? 
And maybe at to the `win-install` command docs that user should check the event log if there are unexpected failures. That is the place where nssm writes. For me this is common thing because .net and iis works the same. So just for users not so familiar with windows.

**Comment by bjrmatos** [comment]
yes, you are right. probably there is nothing different between stdout/stderr output and jsreport log in normal app. i was thinking that storing the stdout/stderr output will be helpful to debug things with `console.log` in cases when user wants to do it from the service. are `stdout/stderr` messages still logged in windows event logs?

**Comment by pofider** [comment]
The stdout is not logged into the event logs. Just the unexpected errors.
I believe developers has many options to get the output logs already.

I've just improved the docs with notes about the event logs and I believe it is fine from our side for now.

If there will be some requests we can reopen.
